apiVersion: v1
kind: Service
metadata:
  name: dagster-service
  labels:
    app: dagster
spec:
  type: NodePort
  selector:
    app: dagster
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000  